# Begin with only the CLI executable, so build/test output cannot mask missing DLLs.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(deployment_dir "${OUTPUT_DIRECTORY}/deployment-${run_id}")
file(MAKE_DIRECTORY "${deployment_dir}")
get_filename_component(executable_name "${EXECUTABLE}" NAME)
file(COPY_FILE "${EXECUTABLE}" "${deployment_dir}/${executable_name}")
set(WINDEPLOYQT_TARGET "${deployment_dir}/${executable_name}")
set(WINDEPLOYQT_HEADLESS ON)
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/RunWindeployQt.cmake")
set(suffix "")
if(WINDEPLOYQT_DEBUG)
    set(suffix d)
endif()
foreach(module IN ITEMS Core Network WebSockets)
    if(NOT EXISTS "${deployment_dir}/Qt6${module}${suffix}.dll")
        message(FATAL_ERROR "CLI deployment is missing Qt ${module}")
    endif()
endforeach()
if(NOT EXISTS "${deployment_dir}/tls/qschannelbackend${suffix}.dll")
    message(FATAL_ERROR "CLI deployment is missing Windows TLS backend")
endif()
set(EXECUTABLE "${WINDEPLOYQT_TARGET}")
set(OUTPUT_DIRECTORY "${deployment_dir}/config")
include("${CMAKE_CURRENT_LIST_DIR}/RoomCliEntryTests.cmake")
