include_guard(GLOBAL)

# Run before project(): a clean checkout does not yet have the pinned compiler
# or Ninja. Output directories are disposable; this cache is independent of them.
if(NOT CMAKE_HOST_WIN32)
    return()
endif()
get_filename_component(_ss_repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(SCREENSHARE_DEPENDENCY_ROOT "${_ss_repo}/.deps" CACHE PATH "Persistent native dependency cache")
option(SCREENSHARE_BOOTSTRAP_DEPENDENCIES "Prepare missing pinned native dependencies during configure" OFF)
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Build configuration" FORCE)
endif()
if(NOT CMAKE_BUILD_TYPE MATCHES "^(Debug|Release)$")
    message(FATAL_ERROR "The pinned native artifacts support Debug or Release; choose a matching preset.")
endif()
string(TOLOWER "${CMAKE_BUILD_TYPE}" _ss_configuration)
file(READ "${_ss_repo}/cmake/dependencies/native-dependencies.json" _ss_native_lock)
string(JSON _ss_qt_version GET "${_ss_native_lock}" qtVersion)
set(_ss_source "${SCREENSHARE_DEPENDENCY_ROOT}/webrtc/checkout/src")
set(_ss_compiler "${_ss_source}/third_party/llvm-build/Release+Asserts/bin/clang-cl.exe")
set(_ss_linker "${_ss_source}/third_party/llvm-build/Release+Asserts/bin/lld-link.exe")
set(_ss_ninja "${_ss_source}/third_party/ninja/ninja.exe")
set(_ss_artifact "${_ss_source}/out/screenshare-${_ss_configuration}")
set(_ss_qt "${SCREENSHARE_DEPENDENCY_ROOT}/Qt/${_ss_qt_version}/msvc2022_64")
set(_ss_vulkan "${SCREENSHARE_DEPENDENCY_ROOT}/Vulkan-Headers/include")
# Older presets stored these defaults in the disposable build directory. Migrate
# only those exact defaults; external SDKs and additional search paths are kept.
function(_ss_migrate_default variable old_path new_path)
    if(DEFINED ${variable})
        file(TO_CMAKE_PATH "${${variable}}" _value)
        if(_value STREQUAL old_path)
            get_property(_type CACHE "${variable}" PROPERTY TYPE)
            if(_type)
                set(${variable} "${new_path}" CACHE ${_type} "Native dependency path" FORCE)
            endif()
            set(${variable} "${new_path}" PARENT_SCOPE)
            message(STATUS "Migrated legacy dependency path: ${variable}")
        endif()
    endif()
endfunction()
set(_ss_old_source "${_ss_repo}/build/webrtc/checkout/src")
foreach(_ss_var CMAKE_C_COMPILER CMAKE_CXX_COMPILER)
    _ss_migrate_default(${_ss_var} "${_ss_old_source}/third_party/llvm-build/Release+Asserts/bin/clang-cl.exe" "${_ss_compiler}")
endforeach()
_ss_migrate_default(CMAKE_LINKER "${_ss_old_source}/third_party/llvm-build/Release+Asserts/bin/lld-link.exe" "${_ss_linker}")
_ss_migrate_default(CMAKE_MAKE_PROGRAM "${_ss_old_source}/third_party/ninja/ninja.exe" "${_ss_ninja}")
_ss_migrate_default(SCREENSHARE_WEBRTC_ARTIFACT_DIR "${_ss_old_source}/out/screenshare-${_ss_configuration}" "${_ss_artifact}")
_ss_migrate_default(Vulkan_INCLUDE_DIR "${_ss_repo}/build/Vulkan-Headers/include" "${_ss_vulkan}")
set(_ss_old_qt "${_ss_repo}/build/Qt/${_ss_qt_version}/msvc2022_64")
get_cmake_property(_ss_variables VARIABLES)
foreach(_ss_var IN LISTS _ss_variables)
    if(_ss_var MATCHES "^Qt6.*_DIR$")
        string(REGEX REPLACE "_DIR$" "" _ss_package "${_ss_var}")
        _ss_migrate_default(${_ss_var} "${_ss_old_qt}/lib/cmake/${_ss_package}" "${_ss_qt}/lib/cmake/${_ss_package}")
    endif()
endforeach()
if(DEFINED CMAKE_PREFIX_PATH)
    set(_ss_prefixes "")
    foreach(_ss_prefix IN LISTS CMAKE_PREFIX_PATH)
        _ss_migrate_default(_ss_prefix "${_ss_old_qt}" "${_ss_qt}")
        list(APPEND _ss_prefixes "${_ss_prefix}")
    endforeach()
    set(CMAKE_PREFIX_PATH "${_ss_prefixes}" CACHE STRING "Native dependency search prefixes" FORCE)
    set(CMAKE_PREFIX_PATH "${_ss_prefixes}")
endif()
set(CMAKE_C_COMPILER "${_ss_compiler}" CACHE FILEPATH "Pinned native C compiler")
set(CMAKE_CXX_COMPILER "${_ss_compiler}" CACHE FILEPATH "Pinned native C++ compiler")
set(CMAKE_LINKER "${_ss_linker}" CACHE FILEPATH "Pinned native linker")
set(CMAKE_MAKE_PROGRAM "${_ss_ninja}" CACHE FILEPATH "Pinned Ninja")
set(CMAKE_PREFIX_PATH "${_ss_qt}" CACHE STRING "Native dependency search prefixes")
set(Qt6_DIR "${_ss_qt}/lib/cmake/Qt6" CACHE PATH "Native Qt package")
set(Vulkan_INCLUDE_DIR "${_ss_vulkan}" CACHE PATH "Pinned Vulkan headers")
set(SCREENSHARE_WEBRTC_ARTIFACT_DIR "${_ss_artifact}" CACHE PATH "Verified WebRTC artifact or SDK")
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDebugDLL CACHE STRING "MSVC CRT")
else()
    set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDLL CACHE STRING "MSVC CRT")
endif()

get_filename_component(_ss_qt_packages "${Qt6_DIR}" DIRECTORY)
set(_ss_required "${CMAKE_CXX_COMPILER}" "${CMAKE_C_COMPILER}" "${CMAKE_LINKER}" "${CMAKE_MAKE_PROGRAM}"
    "${SCREENSHARE_WEBRTC_ARTIFACT_DIR}/screenshare-artifact.json"
    "${SCREENSHARE_WEBRTC_ARTIFACT_DIR}/obj/webrtc.lib" "${SCREENSHARE_WEBRTC_ARTIFACT_DIR}/args.gn"
    "${Vulkan_INCLUDE_DIR}/vulkan/vulkan.h")
set(_ss_qt_components Core Network WebSockets)
if(NOT DEFINED SCREENSHARE_BUILD_QT_UI OR SCREENSHARE_BUILD_QT_UI)
    list(APPEND _ss_qt_components Widgets Svg)
endif()
foreach(_ss_component IN LISTS _ss_qt_components)
    list(APPEND _ss_required "${_ss_qt_packages}/Qt6${_ss_component}/Qt6${_ss_component}Config.cmake")
endforeach()
set(_ss_missing "")
foreach(_ss_file IN LISTS _ss_required)
    if(NOT EXISTS "${_ss_file}")
        list(APPEND _ss_missing "${_ss_file}")
    endif()
endforeach()
if(_ss_missing)
    if(NOT SCREENSHARE_BOOTSTRAP_DEPENDENCIES)
        message(FATAL_ERROR "Native dependencies are missing. Run powershell -NoProfile -ExecutionPolicy Bypass -File scripts/prepare-dependencies.ps1 -Configuration ${CMAKE_BUILD_TYPE} -DependencyRoot \"${SCREENSHARE_DEPENDENCY_ROOT}\", or configure with a standard preset to prepare them automatically. Missing: ${_ss_missing}")
    endif()
    # Never silently download replacements for caller-supplied SDK/toolchain paths.
    if(NOT SCREENSHARE_WEBRTC_ARTIFACT_DIR STREQUAL _ss_artifact OR
       NOT CMAKE_CXX_COMPILER STREQUAL _ss_compiler OR NOT CMAKE_C_COMPILER STREQUAL _ss_compiler OR
       NOT CMAKE_LINKER STREQUAL _ss_linker OR NOT CMAKE_MAKE_PROGRAM STREQUAL _ss_ninja OR
       NOT Qt6_DIR STREQUAL "${_ss_qt}/lib/cmake/Qt6" OR NOT Vulkan_INCLUDE_DIR STREQUAL _ss_vulkan)
        message(FATAL_ERROR "Custom native dependency paths are incomplete. Restore those dependencies or use the default cache. Missing: ${_ss_missing}")
    endif()
    find_program(_ss_powershell NAMES pwsh powershell REQUIRED)
    message(STATUS "Preparing native dependencies in ${SCREENSHARE_DEPENDENCY_ROOT}. First setup downloads Qt/WebRTC and compiles WebRTC; subsequent builds reuse this cache.")
    execute_process(COMMAND "${_ss_powershell}" -NoProfile -ExecutionPolicy Bypass
        -File "${_ss_repo}/scripts/prepare-dependencies.ps1"
        -Configuration "${CMAKE_BUILD_TYPE}" -DependencyRoot "${SCREENSHARE_DEPENDENCY_ROOT}"
        RESULT_VARIABLE _ss_prepared)
    if(NOT _ss_prepared EQUAL 0)
        message(FATAL_ERROR "Native dependency preparation failed. Resolve the error above and configure again; completed downloads are reused.")
    endif()
    foreach(_ss_file IN LISTS _ss_required)
        if(NOT EXISTS "${_ss_file}")
            message(FATAL_ERROR "Dependency preparation was incomplete: ${_ss_file}")
        endif()
    endforeach()
endif()
# The existing WebRTC import still validates source, compiler, ABI, patch, GN
# arguments and library checksums; bootstrap never bypasses that validation.
