include_guard(GLOBAL)

# The dependency build is deliberately separate from application configuration.
# Point this at an output from scripts/build-webrtc.ps1; no download occurs here.
set(SCREENSHARE_WEBRTC_ARTIFACT_DIR "" CACHE PATH "Verified local WebRTC artifact directory")
function(screenshare_import_webrtc)
    if(TARGET ScreenShare::WebRTC)
        return()
    endif()
    if(NOT WIN32 OR NOT MSVC OR NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
        message(FATAL_ERROR "WebRTC requires Windows x64 clang-cl with the MSVC ABI")
    endif()
    set(manifest "${SCREENSHARE_WEBRTC_ARTIFACT_DIR}/screenshare-artifact.json")
    if(NOT EXISTS "${manifest}")
        message(FATAL_ERROR "Missing ${manifest}. Build the pinned dependency with scripts/build-webrtc.ps1 first.")
    endif()
    file(READ "${manifest}" metadata)
    file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../refactor/webrtc-source.json" lock)
    foreach(field schemaVersion sourceRevision configuration architecture runtime standardLibrary compilerSha256 librarySha256 sourceDirectory gnArgumentsSha256 buildPatchSha256)
        string(JSON ${field} ERROR_VARIABLE json_error GET "${metadata}" ${field})
        if(json_error)
            message(FATAL_ERROR "Invalid WebRTC artifact field ${field}: ${json_error}")
        endif()
    endforeach()
    string(JSON expectedRevision GET "${lock}" commit)
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../refactor/webrtc-build.patch" expectedPatchHash)
    if(NOT buildPatchSha256 STREQUAL expectedPatchHash)
        message(FATAL_ERROR "WebRTC build patch changed; rebuild the dependency")
    endif()
    if(NOT EXISTS "${SCREENSHARE_WEBRTC_ARTIFACT_DIR}/args.gn")
        message(FATAL_ERROR "WebRTC artifact is missing its GN arguments")
    endif()
    file(SHA256 "${SCREENSHARE_WEBRTC_ARTIFACT_DIR}/args.gn" actualArgumentsHash)
    if(NOT gnArgumentsSha256 STREQUAL actualArgumentsHash)
        message(FATAL_ERROR "WebRTC GN arguments changed since the artifact was built")
    endif()
    if(NOT schemaVersion EQUAL 1 OR NOT sourceRevision STREQUAL expectedRevision OR
       NOT architecture STREQUAL "x64" OR NOT standardLibrary STREQUAL "msvc")
        message(FATAL_ERROR "WebRTC artifact source/schema/ABI mismatch")
    endif()
    if(NOT configuration STREQUAL CMAKE_BUILD_TYPE)
        message(FATAL_ERROR "WebRTC ${configuration} artifact cannot be used for ${CMAKE_BUILD_TYPE}")
    endif()
    set(expectedRuntime "MultiThreadedDLL")
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(expectedRuntime "MultiThreadedDebugDLL")
    endif()
    if(NOT runtime STREQUAL expectedRuntime OR NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL expectedRuntime)
        message(FATAL_ERROR "Application and WebRTC must use ${expectedRuntime}")
    endif()
    file(SHA256 "${CMAKE_CXX_COMPILER}" actualCompilerHash)
    if(NOT actualCompilerHash STREQUAL compilerSha256)
        message(FATAL_ERROR "Use the exact clang-cl binary from the pinned WebRTC checkout")
    endif()
    set(library "${SCREENSHARE_WEBRTC_ARTIFACT_DIR}/obj/webrtc.lib")
    if(NOT EXISTS "${library}" OR NOT EXISTS "${sourceDirectory}/api/peer_connection_interface.h")
        message(FATAL_ERROR "WebRTC library or matching source headers are missing")
    endif()
    file(SHA256 "${library}" actualLibraryHash)
    if(NOT actualLibraryHash STREQUAL librarySha256)
        message(FATAL_ERROR "WebRTC library checksum mismatch")
    endif()
    add_library(ScreenShare::WebRTC STATIC IMPORTED GLOBAL)
    set_target_properties(ScreenShare::WebRTC PROPERTIES
        IMPORTED_LOCATION "${library}"
        INTERFACE_INCLUDE_DIRECTORIES "${sourceDirectory};${sourceDirectory}/third_party/abseil-cpp;${sourceDirectory}/third_party/libyuv/include;${sourceDirectory}/third_party/opus/src/include;${SCREENSHARE_WEBRTC_ARTIFACT_DIR}/gen"
        INTERFACE_COMPILE_FEATURES cxx_std_20
        INTERFACE_COMPILE_OPTIONS "/EHsc;/GR"
    )
    foreach(field defines systemLibraries)
        string(JSON itemCount LENGTH "${metadata}" ${field})
        set(items "")
        if(itemCount GREATER 0)
            math(EXPR lastIndex "${itemCount} - 1")
            foreach(index RANGE 0 ${lastIndex})
                string(JSON item GET "${metadata}" ${field} ${index})
                list(APPEND items "${item}")
            endforeach()
        endif()
        if(field STREQUAL "defines")
            set_property(TARGET ScreenShare::WebRTC PROPERTY INTERFACE_COMPILE_DEFINITIONS "${items}")
        else()
            set_property(TARGET ScreenShare::WebRTC PROPERTY INTERFACE_LINK_LIBRARIES "${items}")
        endif()
    endforeach()
endfunction()
